PAAS-2926: remove duplicate of provisionning and jcrcommands modules

diff --git a/packages/jahia/migrations/migrate-to-v41.yaml b/packages/jahia/migrations/migrate-to-v41.yaml
--- a/packages/jahia/migrations/migrate-to-v41.yaml
+++ b/packages/jahia/migrations/migrate-to-v41.yaml
@@ -37,6 +37,7 @@ onInstall:
 
   # Actions that require a redeploy
   - upgradeHaproxy            # PAAS-2860
+  - removeOldModuleVersions   # PAAS-2926
 
   # Redeploy and restart actions:
   - if ("${globals.jahiaRollingRedeployNeeded}" == "true"):
@@ -110,6 +111,46 @@ actions:
       data:
         productName: haproxy
         productVersion: ${globals.haproxyVersion}
+
+  removeOldModuleVersions:
+    - getJahiaVersion
+    - isVersionBetween:
+        version: ${globals.jahiaVersion}
+        higher: 8.1.7.0
+        higher_may_equal: false
+        lower: 8.1.3.0
+        lower_may_equal: true
+        res: concernedVersion
+    - if (${globals.concernedVersion}):
+        - if ("${globals.jahiaVersion}" == "8.1.3.0"):
+            set:
+              version: 8.1.3.2
+        - elif ("${globals.jahiaVersion}" == "8.1.5.0"):
+            set:
+              version: 8.1.5.2
+        - elif ("${globals.jahiaVersion}" == "8.1.6.0"):
+            set:
+              version: 8.1.6.1
+        - else:
+            return:
+              type: error
+              message: "Error, unknown jahia version ${globals.jahiaVersion}"
+
+        - enableKarafLogin: "cp, proc"
+        - cmd[cp, proc]: |-
+            for module in "provisioning" "jcrcommands"; do
+              current_versions=$(${globals.karafConsole} cluster:bundle-list -s default |grep $module | awk '{print $10 }')
+              if ! (echo $current_versions | grep -q ${this.version}); then
+                echo "$module/${this.version} is missing and will be installed"
+                ${globals.karafConsole} bundle:install -l 30 mvn:org.jahia.bundles/org.jahia.bundles.$module/${this.version}
+                ${globals.karafConsole} bundle:start org.jahia.bundles.$module/${this.version}
+              fi
+              if (echo $current_versions | grep -q ${globals.jahiaVersion}); then
+                echo "$module/${globals.jahiaVersion} is present and will be unstalled."
+                ${globals.karafConsole} bundle:uninstall org.jahia.bundles.$module/${globals.jahiaVersion}
+              fi
+            done
+        - disableKarafLogin: "cp, proc"
 
 settings:
   fields:
