PAAS-2114: add augmented search datadog checks

diff --git a/packages/jahia/augmented-search-uninstall.yml b/packages/jahia/augmented-search-uninstall.yml
--- a/packages/jahia/augmented-search-uninstall.yml
+++ b/packages/jahia/augmented-search-uninstall.yml
@@ -18,39 +18,40 @@ onInstall:
   - deleteAugSearch
   - removeNodeGroupData
   - destroyESDeployment
+  - disableDatadogAugSearchCheck
 
 actions:
   deleteESConnection:
-  - getPatTokenAndKey
-  - cmd[proc]: |-
-      __secret__API_TOKEN="${globals.__secret__pat_token}"
-      get_current_es_connection() {
-        curl -fLSs http://localhost:8080/modules/graphql \
-          -H "Authorization: APIToken $__secret__API_TOKEN" \
-          -H 'Origin: http://localhost:8080' \
-          -H 'Content-Type: application/json' \
-          -d '{"query":"query { admin { search { currentConnection } } }"}' \
-          | jq -r '.data.admin.search.currentConnection'
-      }
-      curl_delete_es(){
-        curl -fLSs -XDELETE http://localhost:8080/modules/dbconn/elasticsearch/remove/$current_es_connection \
-          -H "Authorization: APIToken $__secret__API_TOKEN" \
-          -H 'Origin: http://localhost:8080' \
-          -H 'Content-Type: application/json' \
-          | jq -r ".success"
-      }
-      current_es_connection=$(get_current_es_connection)
-      if [ "$current_es_connection" = "null" ]; then
-        echo "No ES connection found in AS module, nothing to do"
-        exit 0
-      fi
-      echo "Deleting ES connection"
-      result=$(curl_delete_es)
-      if [ "$result" != "Successfully removed ElasticSearch connection" ]; then
-        echo "Failed to remove the old connection"
-        exit 1
-      fi
-      echo "ES connection is now removed"
+    - getPatTokenAndKey
+    - cmd[proc]: |-
+        __secret__API_TOKEN="${globals.__secret__pat_token}"
+        get_current_es_connection() {
+          curl -fLSs http://localhost:8080/modules/graphql \
+            -H "Authorization: APIToken $__secret__API_TOKEN" \
+            -H 'Origin: http://localhost:8080' \
+            -H 'Content-Type: application/json' \
+            -d '{"query":"query { admin { search { currentConnection } } }"}' \
+            | jq -r '.data.admin.search.currentConnection'
+        }
+        curl_delete_es(){
+          curl -fLSs -XDELETE http://localhost:8080/modules/dbconn/elasticsearch/remove/$current_es_connection \
+            -H "Authorization: APIToken $__secret__API_TOKEN" \
+            -H 'Origin: http://localhost:8080' \
+            -H 'Content-Type: application/json' \
+            | jq -r ".success"
+        }
+        current_es_connection=$(get_current_es_connection)
+        if [ "$current_es_connection" = "null" ]; then
+          echo "No ES connection found in AS module, nothing to do"
+          exit 0
+        fi
+        echo "Deleting ES connection"
+        result=$(curl_delete_es)
+        if [ "$result" != "Successfully removed ElasticSearch connection" ]; then
+          echo "Failed to remove the old connection"
+          exit 1
+        fi
+        echo "ES connection is now removed"
 
   deleteAugSearch:
     - uninstallModule:
@@ -62,3 +63,13 @@ actions:
     - environment.nodegroup.ApplyData[cp]:
         data:
           augsearch: null
+
+  disableDatadogAugSearchCheck:
+    - cmd[proc,cp]: |-
+        check_conf_path="/etc/datadog-agent/conf.d/augmented_search.yaml-disabled"
+        check_conf_path_enabled="/etc/datadog-agent/conf.d/augmented_search.yaml"
+        if [ ! -f $check_conf_path ]; then
+          mv $check_conf_path_enabled $check_conf_path
+          systemctl restart datadog-agent
+        fi
+      user: root
diff --git a/packages/jahia/migrations/migrate-to-v17.yaml b/packages/jahia/migrations/migrate-to-v17.yaml
--- a/packages/jahia/migrations/migrate-to-v17.yaml
+++ b/packages/jahia/migrations/migrate-to-v17.yaml
@@ -35,6 +35,7 @@ onInstall:
   - updateJelasticRedeployConf        # PAAS-1993
   - setImageMagickMemoryLimit         # PAAS-2024
   - upgradeHaproxy                    # PAAS-1879
+  - getAugSearchDatadogCheck          # PAAS-2114
 
   # Actions that require a restart:
   - revertCORSFilter                  # PAAS-2049
@@ -118,7 +119,7 @@ actions:
           -e '/^\s*pidfile\s*/d' \
           -e '/^\s*debug\s*$/d' \
           -e "s#^\s*option httpchk GET.*#$HTTP_CHK_NEWLINE#g" $HAPROXY_CONF_BASE
-      
+
       if [ ! -f $HAPROXY_PRESTART_SCRIPT ]; then
         curl -fLSso $HAPROXY_PRESTART_SCRIPT ${globals.repoRootUrl}/packages/jahia/migrations/v17_assets/haproxy_prestart.sh || exit 1
         chmod +x $HAPROXY_PRESTART_SCRIPT
@@ -149,3 +150,34 @@ actions:
         productName: haproxy
         productVersion: ${globals.haproxy_version}
 
+  getAugSearchDatadogCheck:
+    - getPatTokenAndKey
+    - isAugSearchEnabled
+    - cmd[proc,cp]: |-
+        __secret_pat_token="${globals.__secret__pat_token}"
+        check_conf_path="/etc/datadog-agent/conf.d/augmented_search.yaml-disabled"
+        check_conf_path_enabled="/etc/datadog-agent/conf.d/augmented_search.yaml"
+        check_path="/etc/datadog-agent/checks.d/augmented_search.py"
+        if [ ! -f $check_conf_path ] || [ ! -f check_conf_path_enabled ]; then
+          curl -fLsSo $check_conf_path ${baseUrl}/v17_assets/augmented_search.yaml
+          if [ $? -ne 0 ]; then
+            echo "Failed to get ${baseUrl}/v17_assets/augmented_search.yaml"
+            exit 0
+          fi
+          sed -i "s/jahia_root_token_placeholder/$__secret_pat_token/g" $check_conf_path
+          chmod 640 $check_conf_path
+          chown dd-agent: $check_conf_path
+        fi
+        if [ ! -f $check_path ]; then
+          curl -fLsSo $check_path ${baseUrl}/v17_assets/augmented_search.py
+          if [ $? -ne 0 ]; then
+            echo "Failed to get ${baseUrl}/v17_assets/augmented_search.py"
+            exit 0
+          fi
+          chown dd-agent: $check_path
+        fi
+        if [ "${globals.isAugSearchEnabled}" == "true" ] && [ ! -f check_conf_path_enabled ]; then
+          mv $check_conf_path $check_conf_path_enabled
+          systemctl restart datadog-agent
+        fi
+      user: root
