PAAS-1599: Use cURL to DL files and exit if fails

diff --git a/packages/jahia/link-to-jcustomer.yml b/packages/jahia/link-to-jcustomer.yml
--- a/packages/jahia/link-to-jcustomer.yml
+++ b/packages/jahia/link-to-jcustomer.yml
@@ -137,10 +137,16 @@ actions:
     - cmd[${this}]: |-
         CONF_FILENAME=org.jahia.modules.jexperience.settings-global.cfg
         CONF_PATH="/data/digital-factory-data/karaf/etc/$CONF_FILENAME"
+        CONF_ASSET_URL=${globals.repoRootUrl}/assets/jahia/$CONF_FILENAME
+        # Check if asset URL is correct
+        if (! curl -fIs "$CONF_ASSET_URL" > /dev/null); then
+          >&2 echo "Asset not found"
+          exit 1
+        fi
         # Set up jExperience configuration
         jcustomer_key=${globals.jcustomerKey}
         # The last sed is required to escape backslashes (with a backslash) inside the cfg file
-        wget -qO - ${globals.repoRootUrl}/assets/jahia/$CONF_FILENAME \
+        curl -fLSs "$CONF_ASSET_URL" \
         | sed -r -e 's;(\w+URL\s*=\s*).*;\1http://${globals.unomidns};' \
                    -e "s;[ #]*(\w+\.jCustomerKey\s*=\s*).*;\1${jcustomer_key};" \
                    -e "s;(\w+Password\s*=\s*).*;\1$(echo -n ${globals.unomi_pwd_b64} | base64 -d | sed 's;\\;\\\\;g');" \
