PAAS-1810: not use mixins Vault actions to fetch rewrite rules anymore

diff --git a/packages/jahia/rewrite-rules.yml b/packages/jahia/rewrite-rules.yml
--- a/packages/jahia/rewrite-rules.yml
+++ b/packages/jahia/rewrite-rules.yml
@@ -16,13 +16,16 @@ globals:
   temp_rules_dir: "/var/lib/haproxy/customer.configuration.tmp"
 
 onInstall:
-  - vaultGetRewriteRulesB64
   - setRewritesRules
   - reloadHAProxy
   - removeBackup
 
 actions:
   setRewritesRules:
+    ###### WARNING ######
+    # We are not using Jelastic actions to fetch the rewrite rules on Vault because it doesn't work when
+    # the secret data is too big (Jelastic cannot create the global variable and therefore it fails)
+    #####################
     - cmd [bl]: |-
         # Backup current rule files dir
         mkdir -p ${globals.backup_rules_dir} ${globals.temp_rules_dir}
@@ -30,9 +33,17 @@ actions:
           mv -f ${globals.rules_dir}/* ${globals.backup_rules_dir}
         fi
 
+        # Connect to Vault and check if rules exist
+        VAULT_TOKEN=$(curl -s -XPOST $VAULT_CLUSTER_URL/v1/auth/approle/login --data '{"role_id": "'$VAULT_ROLE_ID'", "secret_id": "'$VAULT_SECRET_ID'"}' | jq -r .auth.client_token)
+        VAULT_SECRET_PATH="paas/customers/$ORGANIZATION_NAME/paas_${env.shortdomain}/haproxy"
+        rules_sets=$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_CLUSTER_URL/v1/kv/data/$VAULT_SECRET_PATH | jq -e .data.data)
+        if [ $? -ne 0 ]; then
+          echo "Failed to fetch secret" >&2
+          exit 0
+        fi
+
         # Get all rules as individual files in temp dir, check md5sum with values from front
         # and handle escape character interpretation while populating rules dir
-        rules_sets=$(echo ${globals.rewriteRulesB64} | base64 -d)
         for rules_set in $(echo $rules_sets | jq -r 'keys[]'); do
           echo "$rules_sets" | jq -r ".\"$rules_set\"" > ${globals.temp_rules_dir}/$rules_set.cfg
         done
