:ninja: Add more info in output

diff --git a/mixins/elasticsearch.yml b/mixins/elasticsearch.yml
--- a/mixins/elasticsearch.yml
+++ b/mixins/elasticsearch.yml
@@ -84,7 +84,7 @@ actions:
           pipelineId=$(echo $response | jq -r .id)
           response=$(curl -LSs "https://circleci.com/api/v2/pipeline/$pipelineId/workflow" -H "Circle-Token: $CCToken")
           if [ "$(echo $response | jq -r '.items[0].status')" == "null" ]; then
-            echo "No workflow created on CircleCI, aborting" >&2
+            echo "No workflow created on CircleCI, aborting. Pipeline ID: $pipelineId. Response: $response" >&2
             exit 1
           fi
           timeout=1200 # 20 minutes
