PAAS-1916: improve module installation and check for specific version of module

diff --git a/mixins/jahia.yml b/mixins/jahia.yml
--- a/mixins/jahia.yml
+++ b/mixins/jahia.yml
@@ -594,6 +594,7 @@ actions:
         resp=$(${this.curl} "localhost/modules/api/bundles/${this.moduleSymname}/*/_localInfo")
         case "$(jq -r ". | length" <<< $resp)" in
           "0") # Means the module is not installed
+            echo "uninstalled"
             ;;
           "") # if response is not JSON, for instance 401 unauthorized
             echo "error"
@@ -601,9 +602,9 @@ actions:
             ;;
           *)
             if jq -r 'to_entries[] | "\(.key);\(.value | .moduleState)"' <<< $resp | grep -q STARTED; then
-              echo "module started"
+              echo "started"
             else
-              echo "module installed"
+              echo "installed"
             fi
             ;;
         esac
@@ -611,11 +612,11 @@ actions:
         - return:
             type: error
             message: "An error occurred during module verification."
-    - elif ("${response.out}" == ""):
-        - log: ${this.moduleSymname} ${this.moduleVersion} is not installed
-        - setGlobals:
-            moduleState: uninstalled
     - else:
+        - log: ${this.moduleSymname} is ${response.out}
+        - setGlobals:
+            moduleState: ${response.out}
+    - if ("${globals.moduleState}" == "started") || ("${globals.moduleState}" == "installed"):
         - if ("${response.out}" == "module started"):
             - setGlobals:
                 moduleState: started
@@ -639,45 +640,131 @@ actions:
         - else:
             - setGlobals:
                 mostRecentInstalledVersion: ${response.out}
-            - log: ${this.moduleSymname} is installed but not running, most recent version installed is v${globals.mostRecentInstalledVersion}
+            - log: ${this.moduleSymname} is installed but not running, most recent version installed is ${globals.mostRecentInstalledVersion}
+
+  checkVersionOfModule:
+    # Checks the state of a module for a specific version: uninstalled, installed or started.
+    # 
+    # Parameters:
+    # - moduleSymname: the symbolic name of the module to upgrade (for instance "distributed-sessions")
+    # - moduleVersion: the version of the module to check
+    # Returns:
+    # - globals.moduleVersionState: 
+    #   - "started" if the specified version of the module is running
+    #   - "installed" if the specified version of the module is installed but not running
+    #   - "uninstalled" if the specified version of the module is not installed
+    - set:
+        curl: 'curl -SsH "Authorization: APIToken ${globals.__secret__pat_token}"'
+    - getPatTokenAndKey
+    - cmd [proc]: |-
+        resp=$(${this.curl} "localhost/modules/api/bundles/${this.moduleSymname}/${this.moduleVersion}/_localInfo")
+        case "$(jq -r .moduleState <<< $resp)" in
+          "") # if response is not JSON, for instance 401 unauthorized
+            echo "error"
+            echo $resp >&2
+            ;;
+          STARTED) # Means the module is running
+            echo "started"
+            ;;
+          null|UNINSTALLED) # null is in case a 404 (but still JSON) is returned (normal behavior)
+            echo "uninstalled"
+            ;;
+          *)
+            echo "installed"
+            ;;
+        esac
+    - if ("${response.out}" == "error"):
+        - return:
+            type: error
+            message: "An error occurred during module verification."
+    - else:
+        - log: ${this.moduleSymname}/${this.moduleVersion} is ${response.out}
+        - setGlobals:
+                moduleState: ${response.out}
 
   installModule:
     # Downloads a module jar file and installs it. The module can also be started at the same time.
+    # If the module is already installed, the installation is skipped, but if the "startModule" parameter is set to true,
+    # then the specified version of the module is started.
     #
     # Parameters:
     #   - moduleSymname: the symbolic name of the module to upgrade (for instance "distributed-sessions")
     #   - moduleVersion: the version of the module to install
     #   - startModule (optional): if the module should be started or not, true or false. Default: false
     #   - jarUrl (optional): the URL to download the jar file. Default: https://store.jahia.com/cms/mavenproxy/private-app-store/org/jahia/modules
-    - set:
-        modulesUrl: https://store.jahia.com/cms/mavenproxy/private-app-store/org/jahia/modules
-        curl: 'curl -SsH "Authorization: APIToken ${globals.__secret__pat_token}"'
-    - if ('${this.startModule.print()}' == ''):
-        set:
-          startModule: "false"
-    - if ('${this.jarUrl.print()}' == ''):
-        set:
-          jarUrl: ""
-    - getPatTokenAndKey
-    - log: Installing ${this.moduleSymname} ${this.moduleVersion}
-    - cmd [proc]: |-
-        if [[ "${this.jarUrl}" == "" ]]; then
-          url="${this.modulesUrl}/${this.moduleSymname}/${this.moduleVersion}/${this.moduleSymname}-${this.moduleVersion}.jar"
-        else
-          url=${this.jarUrl}
-        fi
-        tmp_dir=$(mktemp -d)
-        local_jar_file=$tmp_dir/${this.moduleSymname}-${this.moduleVersion}.jar
-        curl -fLSso $local_jar_file $url >&2
-        if [ $? -ne 0 ]; then
-          echo "error"
+    - checkVersionOfModule:
+        moduleSymname: ${this.moduleSymname}
+        moduleVersion: ${this.moduleVersion}
+    - if ("${globals.moduleVersionState}" == "uninstalled"):
+      - set:
+          modulesUrl: https://store.jahia.com/cms/mavenproxy/private-app-store/org/jahia/modules
+          curl: 'curl -SsH "Authorization: APIToken ${globals.__secret__pat_token}"'
+      - if ('${this.startModule.print()}' == ''):
+          set:
+            startModule: "false"
+      - if ('${this.jarUrl.print()}' == ''):
+          set:
+            jarUrl: ""
+      - getPatTokenAndKey
+      - log: Installing ${this.moduleSymname}/${this.moduleVersion}
+      - cmd [proc]: |-
+          if [[ "${this.jarUrl}" == "" ]]; then
+            url="${this.modulesUrl}/${this.moduleSymname}/${this.moduleVersion}/${this.moduleSymname}-${this.moduleVersion}.jar"
+          else
+            url=${this.jarUrl}
+          fi
+          tmp_dir=$(mktemp -d)
+          local_jar_file=$tmp_dir/${this.moduleSymname}-${this.moduleVersion}.jar
+          curl -fLSso $local_jar_file $url >&2
+          if [ $? -ne 0 ]; then
+            echo "error"
+            rm -rf $tmp_dir
+            exit 0
+          fi
+          resp=$(${this.curl} -XPOST \
+                  --form bundle=@$local_jar_file \
+                  --form start=${this.startModule} \
+                  localhost/modules/api/bundles)
+          case "$(jq -r .bundleInfos <<< $resp)" in
+            "null") # If install failed, there is no bundleInfos attribute in the JSON response
+              echo "error"
+              jq -r .message <<< $resp >&2
+              ;;
+            "") # if response is not JSON, for instance 401 unauthorized
+              echo "error"
+              echo $resp >&2
+              ;;
+            *) # Otherwise it means the module was installed, nothing to do
+              ;;
+          esac
           rm -rf $tmp_dir
-          exit 0
-        fi
-        resp=$(${this.curl} -XPOST \
-                 --form bundle=@$local_jar_file \
-                 --form start=${this.startModule} \
-                 localhost/modules/api/bundles)
+      - if ("${response.out}" == "error"):
+          - return:
+              type: error
+              message: "An error occurred during module installation."
+      - log: ${this.moduleSymname}/${this.moduleVersion} has been installed
+    - elif ("${globals.moduleVersionState}" == "installed"):
+        - log: ${this.moduleSymname}/${this.moduleVersion} is already installed, skipping the installation
+        - if (${this.startModule}):
+            - startModule:
+                moduleSymname: ${this.moduleSymname}
+                moduleVersion: ${this.moduleVersion}
+    - else:
+        - log: ${this.moduleSymname}/${this.moduleVersion} is already running, nothing to do
+
+  startModule:
+    # Starts the specified version of a module.
+    #
+    # Parameters:
+    #   - moduleSymname: the symbolic name of the module to upgrade (for instance "distributed-sessions")
+    #   - moduleVersion: the version of the module to install
+    - set:
+        curl: 'curl -SsH "Authorization: APIToken ${globals.__secret__pat_token}"'
+    - getPatTokenAndKey
+    - log: Starting ${this.moduleSymname}/${this.moduleVersion}
+    - cmd [proc]: |-
+        resp=$(${this.curl} -XPOST -d "" \
+                 "localhost/modules/api/bundles/${this.moduleSymname}/${this.moduleVersion}/_start")
         case "$(jq -r .bundleInfos <<< $resp)" in
           "null") # If install failed, there is no bundleInfos attribute in the JSON response
             echo "error"
@@ -690,12 +777,11 @@ actions:
           *) # Otherwise it means the module was installed, nothing to do
             ;;
         esac
-        rm -rf $tmp_dir
     - if ("${response.out}" == "error"):
         - return:
             type: error
-            message: "An error occurred during module installation."
-    - log: ${this.moduleSymname} ${this.moduleVersion} has been installed
+            message: "An error occurred during module uninstall."
+    - log: ${this.moduleSymname}/${this.moduleVersion} has been started
 
   uninstallModuleVersion:
     # Uninstalls the specified version of a module.
@@ -706,7 +792,7 @@ actions:
     - set:
         curl: 'curl -SsH "Authorization: APIToken ${globals.__secret__pat_token}"'
     - getPatTokenAndKey
-    - log: Uninstalling ${this.moduleSymname} ${this.moduleVersion}
+    - log: Uninstalling ${this.moduleSymname}/${this.moduleVersion}
     - cmd [proc]: |-
         resp=$(${this.curl} -XPOST -d "" \
               "localhost/modules/api/bundles/${this.moduleSymname}/${this.moduleVersion}/_uninstall")
